#!/bin/bash

# Make all scripts executable
chmod +x start.sh test_api.sh validate_setup.py

echo "=================================================="
echo "Async Image Processing Pipeline - Quick Start"
echo "=================================================="
echo ""
echo "✓ Project setup complete!"
echo ""
echo "📋 What's been created:"
echo "  ✓ FastAPI application (app/main.py)"
echo "  ✓ RabbitMQ connection manager"
echo "  ✓ 4 worker types (resize, thumbnail, OCR, AI tagging)"
echo "  ✓ Queue and exchange setup"
echo "  ✓ Docker Compose configuration"
echo "  ✓ Complete documentation"
echo ""
echo "🚀 To get started:"
echo ""
echo "1. Make sure Docker and Docker Compose are installed:"
echo "   docker --version"
echo "   docker-compose --version"
echo ""
echo "2. Navigate to the project directory:"
echo "   cd /Users/faisal/Documents/RND/RabbitMQ-FastAPI"
echo ""
echo "3. Start all services:"
echo "   docker-compose up --build"
echo ""
echo "4. Wait for all services to start (2-3 minutes)"
echo "   Look for: 'api | INFO: Application startup complete'"
echo ""
echo "5. In another terminal, test the API:"
echo "   bash test_api.sh"
echo ""
echo "6. Monitor RabbitMQ Management UI:"
echo "   http://localhost:15672"
echo "   Username: guest"
echo "   Password: guest"
echo ""
echo "📚 Documentation:"
echo "  • README.md          - Complete usage guide"
echo "  • ARCHITECTURE.md    - System architecture details"
echo "  • .env.example       - Configuration template"
echo ""
echo "🔗 Access Points:"
echo "  • API Server:        http://localhost:8000"
echo "  • API Documentation: http://localhost:8000/docs"
echo "  • API Redoc:         http://localhost:8000/redoc"
echo "  • RabbitMQ UI:       http://localhost:15672"
echo ""
echo "💡 Key Features Demonstrated:"
echo "  ✓ Producer-Consumer pattern"
echo "  ✓ Durable queues & persistent messages"
echo "  ✓ ACK/NACK mechanism"
echo "  ✓ Retry logic with retry queues"
echo "  ✓ Dead Letter Queues (DLQ)"
echo "  ✓ Fair dispatch (prefetch_count)"
echo "  ✓ Competing consumers"
echo "  ✓ Simulated failures & recovery"
echo ""
echo "⚡ Useful Commands:"
echo ""
echo "  # View logs"
echo "  docker-compose logs -f api"
echo "  docker-compose logs -f resize_worker_1"
echo ""
echo "  # Scale workers"
echo "  docker-compose up -d --scale resize_worker=3"
echo ""
echo "  # Stop everything"
echo "  docker-compose stop"
echo ""
echo "  # Clean everything (remove containers & volumes)"
echo "  docker-compose down -v"
echo ""
echo "  # Check service status"
echo "  docker-compose ps"
echo ""
echo "=================================================="
echo ""
echo "Ready to start learning RabbitMQ! 🎉"
